# Generated by Django 4.2.6 on 2023-10-09 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game_Metadata",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("releasedate", models.TextField()),
                ("platforms", models.TextField()),
                ("developers", models.TextField()),
                ("genre", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Final_Results",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("totalscore", models.DecimalField(decimal_places=14, max_digits=17)),
                ("numoflists", models.PositiveSmallIntegerField()),
                ("avglistyear", models.PositiveSmallIntegerField()),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_name",
                        to="ggoat.game_metadata",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="final_results",
            constraint=models.UniqueConstraint(
                fields=("rank", "name"), name="unique_game"
            ),
        ),
    ]
